/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2015-07-30 19:00:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class includingFiles_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/variables.jsp", Long.valueOf(1438278448110L));
    _jspx_dependants.put("/copyright.txt", Long.valueOf(1438278823336L));
    _jspx_dependants.put("/manupulations.jsp", Long.valueOf(1438277912471L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Static Include--Conent changes Frequently -->\r\n");
      out.write("\t");
      out.write("Copyright Caveofprogramming.com.");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<p />\r\n");
      out.write("\r\n");
      out.write("\t<!-- Dynamic Include--Content Changes a Lot -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "updates.txt", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--  Most used STATIC include if it's got JAVA code in it that we want to access -->\r\n");
      out.write("\t<!--  If you want variables from JAVA code in include we should only use include -->\r\n");
      out.write("\r\n");
      out.write("\t");


String name = "Sue";


      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<p />\r\n");
      out.write("\r\n");
      out.write("\t");
      out.print(name);
      out.write("\r\n");
      out.write("\t<!--  Must use include JSP tage ,if you don't knowwhat file you want till run time -->\r\n");
      out.write("\t<p />\r\n");
      out.write("\t<strong>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "parameters.jsp", out, false);
      out.write("</strong>\r\n");
      out.write("\t<p />\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");

		for (int i = 0; i < 5; i++) {
	
      out.write("\r\n");
      out.write("\t<p>\r\n");
      out.write("\t\tThis HTML is in a Scriptlet LOOP,iteration:");
      out.print(i);
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");

		String id = request.getParameter("id");
		if (id == null) {
	
      out.write("\r\n");
      out.write("\t<strong>ID parameter Missing</strong>\r\n");
      out.write("\t");

		} else{
	
      out.write("\r\n");
      out.write("\tID parameter is :");
      out.print(id );
      out.write('\r');
      out.write('\n');
      out.write('	');
} 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");

		String ids = request.getParameter("ids");
	
      out.write("\r\n");
      out.write("\t<p />\r\n");
      out.write("\t");

		if (ids == null) {
	
      out.write("\r\n");
      out.write("\t<br>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "idNotFound.html", out, false);
      out.write(";\r\n");
      out.write("\t");

		} else {
	
      out.write("\r\n");
      out.write("\t<br>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "idFound.html", out, false);
      out.write(";\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
